# Problem 7: Connect to the server at 192.168.14.10 on port 3007 and request the flag as in previous problems. The server's response will be of the form "FLAG flag", encrypted with AES-128 in CBC mode and transmitted as raw bytes. The encryption key was generated by taking the MD5 hash of a dictionary word. Find the password that generates the encryption key and decrypt the server's response to extract the flag.

import socket
import binascii
from Crypto.Cipher import AES
from Crypto.Hash import MD5

TCP_IP = '192.168.14.10'
TCP_PORT = 3007

sock = socket.socket(socket.AF_INET,
      socket.SOCK_STREAM)
sock.connect((TCP_IP, TCP_PORT))
sock.send("GET FLAG")
data = sock.recv(1024)
sock.close()

#key = "20 14 03 04 20 14 03 04 20 14 03 04 20 14 03 04"
#key_aes = binascii.a2b_hex(key.replace(' ', ''))[:16]
iv = data[:16]
print iv
data = data[16:]
dictionary = open('/usr/share/dict/words', 'r')
for password in dictionary:
    key = MD5.new(password.strip()).hexdigest()
    key_aes = binascii.a2b_hex(key)
    cipher = AES.new(key_aes, AES.MODE_CBC, iv)
    plaintext = cipher.decrypt(data)
    if 'FLAG' in plaintext:
        print "The password was " + password.strip() + "."
        break
    else:
        print "Tried password " + password.strip() + " and failed."
print "Got message: " + plaintext
